# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='indicado',
            options={'verbose_name_plural': 'Indicados'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='SobreNome',
        ),
        migrations.RemoveField(
            model_name='indicado',
            name='SobreNome',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Arquivo',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='Deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='FeedbackNome',
            field=models.CharField(default='coaching', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='TipoDeFeedback',
            field=models.CharField(choices=[('pre', 'pré-coaching'), ('pos', 'pós-coaching'), ('cus', 'customizado')], default='pre', max_length=12),
        ),
        migrations.AddField(
            model_name='indicado',
            name='Categoria',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicado',
            name='Resposta1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicado',
            name='Resposta2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='WebKey',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='indicado',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='indicado',
            name='Nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='indicado',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='indicado',
            name='WebKey',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
