# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedbacks', '0002_auto_20170114_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.RemoveField(
            model_name='indicado',
            name='Categoria',
        ),
        migrations.AddField(
            model_name='cliente',
            name='CRP',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='TipoDeFeedback',
            field=models.CharField(choices=[('pre', 'pré-coaching'), ('pos', 'pós-coaching'), ('cus', 'customizado')], default='pre', max_length=36),
        ),
        migrations.AddField(
            model_name='indicado',
            name='categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Feedbacks.Categoria'),
            preserve_default=False,
        ),
    ]
