# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Feedbacks', '0003_auto_20170116_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicado',
            name='QuemIndicou',
        ),
        migrations.AddField(
            model_name='categoria',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Feedbacks.Cliente'),
            preserve_default=False,
        ),
    ]
