# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedbacks', '0005_auto_20170122_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicado',
            name='Categ',
            field=models.CharField(choices=[('Amigos', 'Amigos'), ('Família', 'Família'), ('Trabalho', 'Trabalho'), ('Universidade', 'Universidade')], default='Amigos', max_length=36),
        ),
    ]
