# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedbacks', '0006_auto_20170123_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Categorias',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicado',
            name='Categ',
            field=models.CharField(max_length=36),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
